### ISSUE TITLE
Unexpected Internal Error

### ISSUE THREAD

**Issue by reteo** [lawremi/CustomOreGen#110]
Following my new configuration design, I tried replicating the configuration on my Survival Industry setup, but received the following error while generating the game:

```
[20:59:04] [Server thread/ERROR]: Problem loading world config
java.util.regex.PatternSyntaxException: Unexpected internal error near index 8
MISSING\
        ^
	at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_66]
	at java.util.regex.Pattern.compile(Pattern.java:1702) ~[?:1.8.0_66]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_66]
	at java.util.regex.Pattern.compile(Pattern.java:1054) ~[?:1.8.0_66]
	at CustomOreGen.Util.BiomeDescriptor$Descriptor.getPattern(BiomeDescriptor.java:322) ~[BiomeDescriptor$Descriptor.class:?]
	at CustomOreGen.Util.BiomeDescriptor.matchingWeight(BiomeDescriptor.java:144) ~[BiomeDescriptor.class:?]
	at CustomOreGen.Util.BiomeDescriptor.compileMatches(BiomeDescriptor.java:166) ~[BiomeDescriptor.class:?]
	at CustomOreGen.Util.BiomeDescriptor.getTotalMatchWeight(BiomeDescriptor.java:242) ~[BiomeDescriptor.class:?]
	at CustomOreGen.Server.MapGenOreDistribution.validate(MapGenOreDistribution.java:373) ~[MapGenOreDistribution.class:?]
	at CustomOreGen.Server.MapGenVeins.validate(MapGenVeins.java:141) ~[MapGenVeins.class:?]
	at CustomOreGen.Server.ServerState.validateDistributions(ServerState.java:109) [ServerState.class:?]
	at CustomOreGen.Server.ServerState.onServerChanged(ServerState.java:303) [ServerState.class:?]
	at CustomOreGen.Server.ServerState.checkIfServerChanged(ServerState.java:273) [ServerState.class:?]
	at CustomOreGen.ForgeInterface.onLoadWorld(ForgeInterface.java:45) [ForgeInterface.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_ForgeInterface_onLoadWorld_Load.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73) [bsx.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

Any ideas?

**Comment by reteo** [comment]
Never mind.  I found it and now I just want to hide for the next seventy years.
