### ISSUE TITLE
(GREGTECH Ore Gen) Ore block descriptor for CoalBedHintVeins is empty or does not match any registered blocks 

### ISSUE THREAD

**Issue by JalapenoPepper** [lawremi/CustomOreGen#238]
### I have a problem with your mod and Gregtech Community Edition on 1.12.2, it seems to stop the server from generating and loading existing worlds!
What I've tried:

- Deleting the world
- Deleting the configs
- Trying to manually fix this error in COG and Gregtech configs, or stop the coal beds from generation to avoid the error
- Reinstalled whole server

**Nothing helped((**
Please, can you provide some fixes to your mod, just because your mod can't be replaced with other ore generation mods, it have all the functions I need!
MC version: 1.12.2
Forge version: 1.12.2-14.23.5.2847
Gregtech version: 1.12.2-1.8.13.465
COG version: 1.12-1.8.1 and 1.8.0 tried

Error log available below
```
[00:02:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:02:32] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:02:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[00:02:32] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[00:02:32] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_40, running on Linux:amd64:4.19.0-5-amd64, installed at /home/minecraft/jdk/java-se-8u40-ri/jre
[00:02:33] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[00:02:33] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[00:02:33] [main/INFO] [FML]: Searching /home/minecraft/Server_1.12.2/./mods for mods
[00:02:33] [main/INFO] [FML]: Searching /home/minecraft/Server_1.12.2/./mods/1.12.2 for mods
[00:02:33] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[00:02:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in gregtech-1.12.2-1.8.13.465.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[00:02:33] [main/WARN] [FML]: The coremod GTCELoadingPlugin (gregtech.common.asm.GTCELoadingPlugin) is not signed!
[00:02:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:02:33] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[00:02:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:02:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:02:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:02:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:02:36] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[00:02:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:02:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:02:36] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[00:02:36] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[00:02:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:02:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:02:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:02:38] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[00:02:46] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.12.2
[00:02:46] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2847 Initialized
[00:02:46] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[00:02:46] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[00:02:46] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[00:02:46] [Server thread/INFO] [FML]: Searching /home/minecraft/Server_1.12.2/./mods for mods
[00:02:46] [Server thread/INFO] [FML]: Searching /home/minecraft/Server_1.12.2/./mods/1.12.2 for mods
[00:02:47] [Server thread/WARN] [FML]: Mod codechickenlib is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.3.358
[00:02:47] [Server thread/INFO] [FML]: Mod customoregen is missing the required element 'name'. Substituting customoregen
[00:02:47] [Server thread/WARN] [FML]: Mod gregtech is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.8.13.465
[00:02:48] [Server thread/INFO] [FML]: Forge Mod Loader has identified 8 mods to load
[00:02:48] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[00:02:48] [Server thread/WARN] [FML]: Missing English translation for codechickenlib: assets/codechickenlib/lang/en_us.lang
[00:02:48] [Server thread/WARN] [FML]: Missing English translation for customoregen: assets/customoregen/lang/en_us.lang
[00:02:49] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, codechickenlib, customoregen, gregtech, rtg] at CLIENT
[00:02:49] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, codechickenlib, customoregen, gregtech, rtg] at SERVER
[00:02:50] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[00:02:50] [Server thread/INFO] [FML]: Found 1169 ObjectHolder annotations
[00:02:50] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[00:02:50] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[00:02:50] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[00:02:50] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[00:02:51] [Server thread/INFO] [gregtech]: 0 annotated material handlers registered
[00:02:51] [Server thread/INFO] [gregtech]: Freezing material registry...
[00:02:53] [Server thread/INFO] [gregtech]: Registering MetaTileEntities
[00:02:54] [Server thread/INFO] [gregtech]: Registering Blocks...
[00:02:54] [Server thread/INFO] [FML]: Applying holder lookups
[00:02:54] [Server thread/INFO] [FML]: Holder lookups applied
[00:02:54] [Server thread/INFO] [gregtech]: Registering Items...
[00:02:55] [Server thread/INFO] [FML]: Applying holder lookups
[00:02:55] [Server thread/INFO] [FML]: Holder lookups applied
[00:02:55] [Server thread/INFO] [FML]: Applying holder lookups
[00:02:55] [Server thread/INFO] [FML]: Holder lookups applied
[00:02:55] [Server thread/INFO] [FML]: Applying holder lookups
[00:02:55] [Server thread/INFO] [FML]: Holder lookups applied
[00:02:55] [Server thread/INFO] [FML]: Injecting itemstacks
[00:02:55] [Server thread/INFO] [FML]: Itemstack injection complete
[00:02:55] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[00:02:55] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[00:02:55] [Server thread/INFO] [minecraft/DedicatedServer]: Generating keypair
[00:02:55] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
[00:02:55] [Server thread/INFO] [minecraft/NetworkSystem]: Using epoll channel type
[00:02:55] [Server thread/INFO] [gregtech]: Registering ore dictionary...
[00:02:56] [Server thread/INFO] [gregtech]: Registering OreDict entries.
[00:02:56] [Server thread/INFO] [gregtech]: Registering recipes...
[00:02:56] [Server thread/INFO] [gregtech]: Modifying vanilla recipes according to config. DON'T BE SCARED OF FML's WARNING ABOUT DANGEROUS ALTERNATIVE PREFIX.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `bucket`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `heavy_weighted_pressure_plate`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `light_weighted_pressure_plate`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_door`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_trapdoor`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `cauldron`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `hopper`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `iron_bars`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `bowl`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `paper`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `sugar`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:56] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `flint_and_steel`, expected `gregtech`. This could be a intended override, but in most cases indicates a broken mod.
[00:02:57] [Server thread/INFO] [gregtech]: Running early material handlers...
[00:02:59] [Server thread/INFO] [gregtech]: Running late material handlers...
[00:02:59] [Server thread/INFO] [FML]: Applying holder lookups
[00:02:59] [Server thread/INFO] [FML]: Holder lookups applied
[00:02:59] [Server thread/INFO] [gregtech]: Initializing ore generation registry...
[00:02:59] [Server thread/INFO] [gregtech]: Reloading ore generation files from config...
[00:02:59] [Server thread/INFO] [gregtech]: Loaded 53 worldgen definitions
[00:03:00] [Server thread/INFO] [gregtech]: Registering cover behaviors...
[00:03:00] [Server thread/INFO] [gregtech]: Registering dungeon loot...
[00:03:00] [Server thread/INFO] [FML]: Injecting itemstacks
[00:03:00] [Server thread/INFO] [FML]: Itemstack injection complete
[00:03:00] [Server thread/INFO] [customoregen]: Loading global config '/home/minecraft/Server_1.12.2/config/CustomOreGen' ...
[00:03:00] [Forge Version Check/INFO] [forge.VersionCheck]: [codechickenlib] Starting version check at http://chickenbones.net/Files/notification/version.php?query=forge&version=1.12&file=CodeChickenLib
[00:03:03] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 8 mods
[00:03:03] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "NW"
[00:03:04] [Server thread/INFO] [FML]: Loading dimension 0 (NW) (net.minecraft.server.dedicated.DedicatedServer@1ac01b6b)
[00:03:04] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[00:03:05] [Server thread/INFO] [RTG]: World Seed: -6299757100929148188
[00:03:05] [Server thread/INFO] [customoregen]: Loading config data for dimension './NW/DIM0' ...
[00:03:06] [Server thread/ERROR] [customoregen]: Problem loading world config
java.lang.IllegalStateException: *Ore block descriptor for CoalBedHintVeins is empty or does not match any registered blocks.*
	at CustomOreGen.Server.MapGenOreDistribution.validate(MapGenOreDistribution.java:371) ~[MapGenOreDistribution.class:?]
	at CustomOreGen.Server.MapGenVeins.validate(MapGenVeins.java:142) ~[MapGenVeins.class:?]
	at CustomOreGen.Server.ServerState.validateDistributions(ServerState.java:110) [ServerState.class:?]
	at CustomOreGen.Server.ServerState.onServerChanged(ServerState.java:313) [ServerState.class:?]
	at CustomOreGen.Server.ServerState.checkIfServerChanged(ServerState.java:284) [ServerState.class:?]
	at CustomOreGen.ForgeInterface.onLoadWorld(ForgeInterface.java:48) [ForgeInterface.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_ForgeInterface_onLoadWorld_Load.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

_I'll be very appreciated to talk about this error and how to fix it. Thank you!_

**Comment by lawremi** [comment]
The configuration file probably needs to be updated. Note that the mod automatically copies fresh XML files from its jar file on every load. If you already know how to fix the config, you could make a fork of this repository, fix it, and submit a pull request.

**Comment by JalapenoPepper** [comment]
Sorry, but I'm not sure how to do it, can you help me with that?

**Comment by JalapenoPepper** [comment]
> The configuration file probably needs to be updated. Note that the mod automatically copies fresh XML files from its jar file on every load. If you already know how to fix the config, you could make a fork of this repository, fix it, and submit a pull request.

I just need to mention, that I've tried to delete config files in /config directiory, so the mod pulled default config files from its jar, and nothing happened - the error still persists.

**Comment by lawremi** [comment]
The configuration is out of date, in the mod itself, because Gregtech changed their block identifiers. I'm not going to have time to fix this, but if someone wants to contribute something, I'd be happy to accept a pull request.
