### ISSUE TITLE
Crash in SP

### ISSUE THREAD

**Issue by LemADEC** [lawremi/CustomOreGen#45]
I've had this crash when debugging my custom module for GC Mars:
Using CustomOreGenRevived-1.6.4-1.0.25.jar

```
2014-09-30 02:32:56 [INFOS] [STDERR] net.minecraft.util.ReportedException: Ticking memory connection
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:63)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-09-30 02:32:56 [INFOS] [STDERR] Caused by: java.lang.RuntimeException: Attempting to rotate into a null vector
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Util.Transform.rotateZInto(Transform.java:366)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenClusters$ClusterComponent.buildWireframe(MapGenClusters.java:187)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution$StructureGroup.buildWireframes(MapGenOreDistribution.java:694)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution$StructureGroup.<init>(MapGenOreDistribution.java:592)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution.func_75049_b(MapGenOreDistribution.java:464)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution.recursiveGenerate2(MapGenOreDistribution.java:436)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution.func_75036_a(MapGenOreDistribution.java:411)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.MapGenOreDistribution.generate(MapGenOreDistribution.java:210)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.Server.ServerState.getDebuggingGeometryData(ServerState.java:219)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at CustomOreGen.mod_CustomOreGen.serverCustomPayload(mod_CustomOreGen.java:218)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at cpw.mods.fml.common.modloader.ModLoaderPacketHandler.onPacketData(ModLoaderPacketHandler.java:35)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:1130)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
2014-09-30 02:32:56 [INFOS] [STDERR] 	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
2014-09-30 02:32:56 [INFOS] [STDERR] 	... 6 more
2014-09-30 02:32:56 [GRAVE] [Minecraft-Server] Encountered an unexpected exception ReportedException
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:63)
	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.RuntimeException: Attempting to rotate into a null vector
	at CustomOreGen.Util.Transform.rotateZInto(Transform.java:366)
	at CustomOreGen.Server.MapGenClusters$ClusterComponent.buildWireframe(MapGenClusters.java:187)
	at CustomOreGen.Server.MapGenOreDistribution$StructureGroup.buildWireframes(MapGenOreDistribution.java:694)
	at CustomOreGen.Server.MapGenOreDistribution$StructureGroup.<init>(MapGenOreDistribution.java:592)
	at CustomOreGen.Server.MapGenOreDistribution.func_75049_b(MapGenOreDistribution.java:464)
	at CustomOreGen.Server.MapGenOreDistribution.recursiveGenerate2(MapGenOreDistribution.java:436)
	at CustomOreGen.Server.MapGenOreDistribution.func_75036_a(MapGenOreDistribution.java:411)
	at CustomOreGen.Server.MapGenOreDistribution.generate(MapGenOreDistribution.java:210)
	at CustomOreGen.Server.ServerState.getDebuggingGeometryData(ServerState.java:219)
	at CustomOreGen.mod_CustomOreGen.serverCustomPayload(mod_CustomOreGen.java:218)
	at cpw.mods.fml.common.modloader.ModLoaderPacketHandler.onPacketData(ModLoaderPacketHandler.java:35)
	at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
	at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
	at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
	at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:1130)
	at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	... 6 more
```

**Comment by lawremi** [comment]
Please reopen if this is still happening in 1.7.

**Comment by LemADEC** [comment]
You reproduce it when length or radius is too small or nul as far as I remember.
